### ISSUE TITLE
[Feature] Support async query execution in DSL API

### ISSUE THREAD

**Issue by omarkad2** [omarkad2/charybdis#11]
Create a non-blocking method in the DSL API, that returns as soon as the query is sent. It must return a Future with the result of the query.

**Comment by ushachengan** [comment]
Hi, Can you assign this issue to me? I can help with this. Thanks

**Comment by omarkad2** [comment]
I'm sorry I've already started it, feel free to take one of the other issues

**Comment by ushachengan** [comment]
no worries, Thanks @omarkad2 for letting me know.
