### ISSUE TITLE
[Tech] Add checkstyle plugin

### ISSUE THREAD

**Issue by omarkad2** [omarkad2/charybdis#12]
Enforce checkstyle using the maven plugin

**Comment by rangolucas** [comment]
I'm willing to do this. Can you assign me?

**Comment by omarkad2** [comment]
Done

**Comment by rangolucas** [comment]
@omarkad2 I've just seen Checkstyle is enforced in branch misc/checkstyle. Wouldn't merging that branch solve this issue?

**Comment by omarkad2** [comment]
@rangolucas Actually it doesn't build, I tried to add some restrictions to an existent checkstyle file but didn't succeed. In this issue we start from scratch we try to add the plugin and then we can start adding restrictions (enforce 2 spaces for indentation, 1 line break between class declaration and imports, enforce curly braces after control flow statements ...) so to keep it adequate with what I have in the code base.

**Comment by rangolucas** [comment]
@omarkad2 please read my comment in the [pull request](https://github.com/omarkad2/charybdis/pull/20).
